name: JavaScript CI with npm

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 19.8.1
        uses: actions/setup-node@v2
        with:
          node-version: 19.8.1
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
